# Generated by Django 2.1.3 on 2019-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do Feriado.')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Horário de Usuário',
                'verbose_name_plural': 'Horário de Usuários',
            },
        ),
    ]
