# Generated by Django 2.1.3 on 2019-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='kind',
            field=models.TextField(choices=[('7', 'Feriado'), ('9', 'Compensação')], max_length=2, verbose_name='Tipo de data'),
        ),
    ]
