# Generated by Django 2.1.3 on 2019-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workscheduleitem',
            name='week_day',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta'), ('6', 'Sábado')], default=0, max_length=1, verbose_name='Dia Semana'),
            preserve_default=False,
        ),
    ]
