# Generated by Django 2.1.3 on 2019-03-12 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190312_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
