# Generated by Django 2.1.3 on 2019-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='entrada',
            field=models.TimeField(max_length=5, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida',
            field=models.TimeField(max_length=5, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='saida_almoco',
            field=models.TimeField(max_length=5, verbose_name='Saída almoço'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='volta_almoco',
            field=models.TimeField(max_length=5, verbose_name='Volta almoço'),
        ),
    ]
