# Generated by Django 2.1.3 on 2019-03-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190309_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='kind',
        ),
    ]
