# Generated by Django 2.1.3 on 2019-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feriado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriado',
            options={'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
        migrations.AddField(
            model_name='feriado',
            name='abbreviated_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dia/Mês dd/mm'),
        ),
    ]
