# Generated by Django 2.1.3 on 2019-02-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workscheduleitem_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workscheduleitem',
            name='week_day',
            field=models.CharField(choices=[('6', 'Domingo'), ('0', 'Segunda'), ('1', 'Terça'), ('2', 'Quarta'), ('3', 'Quinta'), ('4', 'Sexta'), ('5', 'Sábado')], max_length=1, verbose_name='Dia Semana'),
        ),
    ]
