# Generated by Django 2.1.3 on 2019-02-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190217_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Período')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuário', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Visita',
                'verbose_name_plural': 'Fichas de Visita',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField(max_length=5, verbose_name='Entrada')),
                ('saida_almoco', models.TimeField(max_length=5, verbose_name='Saída almoço')),
                ('volta_almoco', models.TimeField(max_length=5, verbose_name='Volta almoço')),
                ('saida', models.TimeField(max_length=5, verbose_name='Saída')),
                ('workschedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.WorkSchedule', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Ficha de Visita Detalhe',
                'verbose_name_plural': 'Fichas de Visita Detalhe',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('period', 'user')},
        ),
    ]
