# Generated by Django 2.1.3 on 2019-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190306_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='permanent',
            field=models.BooleanField(default=True, verbose_name='Feriado fixo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feriado',
            name='abbreviated_date',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dia/Mês dd/mm'),
        ),
    ]
