# Generated by Django 2.1.3 on 2019-03-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190306_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workscheduleitem',
            unique_together={('workschedule', 'day')},
        ),
    ]
