# Generated by Django 2.1.3 on 2019-02-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190217_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workscheduleitem',
            name='entrada',
            field=models.TimeField(blank=True, max_length=5, null=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='workscheduleitem',
            name='saida',
            field=models.TimeField(blank=True, max_length=5, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='workscheduleitem',
            name='saida_almoco',
            field=models.TimeField(blank=True, max_length=5, null=True, verbose_name='Saída almoço'),
        ),
        migrations.AlterField(
            model_name='workscheduleitem',
            name='volta_almoco',
            field=models.TimeField(blank=True, max_length=5, null=True, verbose_name='Volta almoço'),
        ),
        migrations.AlterField(
            model_name='workscheduleitem',
            name='workschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.WorkSchedule', verbose_name='Ficha'),
        ),
    ]
