# Generated by Django 2.1.3 on 2019-03-13 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20190312_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição do Dia.')),
                ('date', models.DateField(verbose_name='Data')),
                ('abbreviated_date', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dia/Mês dd/mm')),
                ('permanent', models.BooleanField(verbose_name='Feriado fixo')),
                ('kind', models.CharField(choices=[('6', 'Domingo'), ('0', 'Segunda'), ('1', 'Terça'), ('2', 'Quarta'), ('3', 'Quinta'), ('4', 'Sexta'), ('5', 'Sábado'), ('7', 'Feriado'), ('8', 'Faltou'), ('9', 'Compensação')], max_length=1, verbose_name='Tipo de data')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='Users', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Feriado/Sábado compensado',
                'verbose_name_plural': 'Feriados/Sábados compensados',
            },
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='users',
        ),
        migrations.AlterField(
            model_name='feriado',
            name='kind',
            field=models.CharField(choices=[('6', 'Domingo'), ('0', 'Segunda'), ('1', 'Terça'), ('2', 'Quarta'), ('3', 'Quinta'), ('4', 'Sexta'), ('5', 'Sábado'), ('7', 'Feriado'), ('8', 'Faltou'), ('9', 'Compensação')], max_length=1, verbose_name='Tipo de data'),
        ),
    ]
