# Generated by Django 2.1.3 on 2019-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190217_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='entrada',
            new_name='entrance',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='saida',
            new_name='exit',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='saida_almoco',
            new_name='lunch_entrance',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='volta_almoco',
            new_name='lunch_out',
        ),
        migrations.RenameField(
            model_name='workscheduleitem',
            old_name='entrada',
            new_name='entrance',
        ),
        migrations.RenameField(
            model_name='workscheduleitem',
            old_name='saida',
            new_name='exit',
        ),
        migrations.RenameField(
            model_name='workscheduleitem',
            old_name='saida_almoco',
            new_name='lunch_entrance',
        ),
        migrations.RenameField(
            model_name='workscheduleitem',
            old_name='volta_almoco',
            new_name='lunch_out',
        ),
        migrations.AddField(
            model_name='workscheduleitem',
            name='day',
            field=models.DateField(default='2019-02-01', verbose_name='Dt. Agenda'),
            preserve_default=False,
        ),
    ]
