# Generated by Django 2.1.3 on 2019-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190308_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='kind',
            field=models.CharField(choices=[('7', 'Feriado'), ('9', 'Compensação')], max_length=100, verbose_name='Tipo de data'),
        ),
    ]
