# Generated by Django 2.1.3 on 2019-03-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdalterdata', models.IntegerField(db_index=True, unique=True, verbose_name='Cód. Alterdata')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='E-Mail')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='Cep')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('is_representative', models.BooleanField(verbose_name='É representante?')),
                ('last_search', models.CharField(blank=True, max_length=11, null=True, verbose_name='Última pesquisa.')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em.')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('level', models.CharField(choices=[('0', 'Dependencia'), ('1', 'Confianca'), ('2', 'Comprometimento'), ('3', 'Preditiva')], default='0', max_length=15, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ('-level',),
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=200, verbose_name='Período')),
                ('researched', models.CharField(max_length=200, verbose_name='Entrevistado')),
                ('participation_on', models.DateField(auto_now_add=True, verbose_name='Período da pesquisa')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='core.Client')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ('-participation_on',),
            },
        ),
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField(verbose_name='Resposta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pergunta', to='core.Question', verbose_name='Pergunta')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Periodo', to='core.Search', verbose_name='Período da Pesquisa')),
            ],
            options={
                'verbose_name': 'Pesquisa Detalhe',
                'verbose_name_plural': 'Pesquisas Detalhe',
                'ordering': ('-question',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='products', to='core.Product', verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Client', verbose_name='Representante'),
        ),
        migrations.AlterUniqueTogether(
            name='searchitem',
            unique_together={('search', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('search_key', 'person')},
        ),
    ]
