# Generated by Django 2.1.3 on 2018-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('0', 'Dependencia'), ('1', 'Confianca'), ('2', 'Comprometimento'), ('3', 'Preditiva')], default='0', max_length=15, verbose_name='Nível'),
        ),
    ]
