# Generated by Django 2.1.3 on 2019-03-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_representative',
            field=models.BooleanField(blank=True, null=True, verbose_name='É representante?'),
        ),
    ]
