# Generated by Django 2.1.3 on 2019-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190314_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_representative',
            field=models.BooleanField(default=1, verbose_name='É representante?'),
            preserve_default=False,
        ),
    ]
