# Generated by Django 2.1.3 on 2018-11-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181118_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='response',
            field=models.BooleanField(verbose_name='Resposta'),
        ),
    ]
