# Generated by Django 2.1.3 on 2019-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190121_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='response',
            field=models.BooleanField(verbose_name='Resposta'),
        ),
        migrations.AlterUniqueTogether(
            name='searchitem',
            unique_together={('search', 'question', 'response')},
        ),
    ]
