# Generated by Django 2.1.3 on 2018-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181118_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='response',
            field=models.BooleanField(choices=[('V', 'Verdadeiro'), ('F', 'Falso'), ('I', 'Indefinido')], default='False', max_length=1, verbose_name='Resposta'),
        ),
    ]
