# Generated by Django 2.1.3 on 2019-01-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190122_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchitem',
            unique_together={('search', 'question')},
        ),
    ]
