# Generated by Django 2.1.3 on 2019-02-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190208_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='E-Mail'),
        ),
    ]
