# Generated by Django 2.1.3 on 2018-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181118_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='response',
            field=models.CharField(choices=[('V', 'Verdadeiro'), ('F', 'Falso'), ('I', 'Indefinido')], default='I', max_length=1, verbose_name='Resposta'),
        ),
    ]
