# Generated by Django 2.1.3 on 2018-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181118_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='core.Person')),
            ],
            options={
                'verbose_name': 'Email da Pessoa',
                'verbose_name_plural': 'Emails das Pessoas',
                'ordering': ('email',),
            },
        ),
        migrations.AlterField(
            model_name='search',
            name='response',
            field=models.BooleanField(verbose_name='Resposta'),
        ),
    ]
