# Generated by Django 2.1.3 on 2019-02-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190209_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_representative',
            field=models.BooleanField(default=False, verbose_name='É representante?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=10, verbose_name='Estado'),
        ),
    ]
