# Generated by Django 2.1.3 on 2019-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190209_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sistem',
        ),
        migrations.AddField(
            model_name='client',
            name='system',
            field=models.CharField(choices=[('0', 'Pack'), ('1', 'Shop'), ('2', 'IShop'), ('3', 'Immobile'), ('4', 'Bimer')], max_length=10, null=True, verbose_name='Sistema'),
        ),
    ]
