# Generated by Django 2.1.3 on 2019-02-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190211_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='neighborhood',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='zip_code',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='public_place',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='numero',
        ),
    ]
