# Generated by Django 2.1.3 on 2019-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190211_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='products', to='core.Product', verbose_name='Produtos'),
        ),
    ]
